[project]
name = "redpanda-horizon-forwarder"
version = "0.1.0"
description = "Forwards data from Redpanda to Horizon"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confluent-kafka>=2.13.0",
    "horizon-data-core>=4.0.1",
    "typer>=0.21.1",
]
